// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8hJWALBkKUeeBQwPGDeQHS
// Component: Gg20TNQjnwiE
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateStateOnChangeProp,
  generateStateValueProp,
  hasVariant,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import ThemeBtn from "../../ThemeBtn"; // plasmic-import: OFOxy67RyMdT/component
import { useScreenVariants as useScreenVariantso8ReeXvTrpRu } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: o8REEXvTrpRu/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 8hJWALBkKUeeBQwPGDeQHS/projectcss
import sty from "./PlasmicListadoDeProductos.module.css"; // plasmic-import: Gg20TNQjnwiE/css
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: LvBixuLJ8d5o/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: UEYjHwO6Y9Mk/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: HTOOEs3MCSuB/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: h4CdY3HItaug/icon
import Icon7Icon from "./icons/PlasmicIcon__Icon7"; // plasmic-import: uTYttWNaEUUI/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: J0B87WZBRhbs/icon
import Icon9Icon from "./icons/PlasmicIcon__Icon9"; // plasmic-import: lruOCJHd5GHh/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: CWXe1ywOBmQJ/icon
import image31Nq0AaRzFlL from "./images/image3.jpg"; // plasmic-import: 1nq0aaRZFl-L/picture
import image4ChZz2ZI7IrSj from "./images/image4.jpg"; // plasmic-import: ChZz2zI7IrSJ/picture
import image5DtXZoSdgy4Iq from "./images/image5.jpg"; // plasmic-import: DtXZoSdgy4iq/picture
import image60S8ELaRh2RHd from "./images/image6.jpg"; // plasmic-import: 0s8eLaRh2rHd/picture
import image7WwGrmnh8YS from "./images/image7.jpg"; // plasmic-import: Ww-GRMNH8Y_S/picture
import image8TqfoWSxQcGs from "./images/image8.jpg"; // plasmic-import: _TqfoWSxQCGs/picture
import image9MTcGgEpViCi from "./images/image9.jpg"; // plasmic-import: m-tcGgEpViCi/picture
import image10MW1JukGssZH from "./images/image10.jpg"; // plasmic-import: mW1JukGSS-zH/picture
import image11Aryfpjf4F29L from "./images/image11.jpg"; // plasmic-import: ARYFPJF4F29L/picture
import image12JImdpulIjby9 from "./images/image12.webp"; // plasmic-import: JImdpulIJBY9/picture

createPlasmicElementProxy;

export const PlasmicListadoDeProductos__VariantProps = new Array();

export const PlasmicListadoDeProductos__ArgProps = new Array();

const $$ = {};

function PlasmicListadoDeProductos__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "textbox.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantso8ReeXvTrpRu()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <Stack__
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"logo"}
            data-plasmic-override={overrides.logo}
            className={classNames(projectcss.all, sty.logo)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames(projectcss.all, sty.container)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"row"}
                data-plasmic-override={overrides.row}
                hasGap={true}
                className={classNames(projectcss.all, sty.row)}
              >
                <div className={classNames(projectcss.all, sty.column___2QTpH)}>
                  <div
                    data-plasmic-name={"menu"}
                    data-plasmic-override={overrides.menu}
                    className={classNames(projectcss.all, sty.menu)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__egjI
                      )}
                      href={"https://www.plasmic.app/"}
                      platform={"react"}
                    >
                      {"Stories"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__dTnS2
                      )}
                      href={"https://www.plasmic.app/"}
                      platform={"react"}
                    >
                      {"Categories"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__oIsf9
                      )}
                      href={"https://www.plasmic.app/"}
                      platform={"react"}
                    >
                      {"Recipes"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__s7Dxd
                      )}
                      href={"https://www.plasmic.app/"}
                      platform={"react"}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "About"
                        : "Recipes"}
                    </PlasmicLink__>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__cvtYn)}>
                  <div
                    data-plasmic-name={"socialSection"}
                    data-plasmic-override={overrides.socialSection}
                    className={classNames(projectcss.all, sty.socialSection)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kjZ3B)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__nzG7D)}
                        onClick={async event => {
                          const $steps = {};
                          $steps["goToPage"] = true
                            ? (() => {
                                const actionArgs = {};
                                return (({ destination }) => {
                                  if (
                                    typeof destination === "string" &&
                                    destination.startsWith("#")
                                  ) {
                                    document
                                      .getElementById(destination.substr(1))
                                      .scrollIntoView({ behavior: "smooth" });
                                  } else {
                                    location.assign(destination);
                                  }
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["goToPage"] != null &&
                            typeof $steps["goToPage"] === "object" &&
                            typeof $steps["goToPage"].then === "function"
                          ) {
                            $steps["goToPage"] = await $steps["goToPage"];
                          }
                        }}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__t8NxU)}
                    >
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg___3GeEm)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__svD)}
                    >
                      <Icon5Icon
                        className={classNames(projectcss.all, sty.svg__mjvlc)}
                        role={"img"}
                      />
                    </div>
                  </div>
                </div>
              </Stack__>
            </div>
          </div>
          <div
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            className={classNames(projectcss.all, sty.hero)}
          >
            <div
              data-plasmic-name={"container2"}
              data-plasmic-override={overrides.container2}
              className={classNames(projectcss.all, sty.container2)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__wpsBn)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__itezB
                  )}
                >
                  {"Choose the best."}
                </div>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__rhQj1
                  )}
                >
                  {"Healthy cooking."}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lkyNv
                  )}
                >
                  {
                    "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
                  }
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"hero2"}
            data-plasmic-override={overrides.hero2}
            className={classNames(projectcss.all, sty.hero2)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__v1Z6D)}>
              <div
                data-plasmic-name={"nuestroTitulo"}
                data-plasmic-override={overrides.nuestroTitulo}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.nuestroTitulo
                )}
              >
                {"REAFACIONARIA SOL"}
              </div>
              <h3
                data-plasmic-name={"direccionesHidraulicas"}
                data-plasmic-override={overrides.direccionesHidraulicas}
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.direccionesHidraulicas
                )}
              >
                {"DIRECCIONES HIDRAULICAS,COLISION "}
              </h3>
            </div>
          </div>
          <div
            data-plasmic-name={"blog"}
            data-plasmic-override={overrides.blog}
            className={classNames(projectcss.all, sty.blog)}
          >
            <div
              data-plasmic-name={"container3"}
              data-plasmic-override={overrides.container3}
              className={classNames(projectcss.all, sty.container3)}
            >
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__dvCie
                )}
              >
                {"Featured posts"}
              </h1>
              <Stack__
                as={"div"}
                data-plasmic-name={"row2"}
                data-plasmic-override={overrides.row2}
                hasGap={true}
                className={classNames(projectcss.all, sty.row2)}
              >
                <div className={classNames(projectcss.all, sty.column___9CMjY)}>
                  <div
                    data-plasmic-name={"blogCard"}
                    data-plasmic-override={overrides.blogCard}
                    className={classNames(projectcss.all, sty.blogCard)}
                    onClick={async event => {
                      const $steps = {};
                      $steps["goToHomepage"] = true
                        ? (() => {
                            const actionArgs = { destination: `/` };
                            return (({ destination }) => {
                              if (
                                typeof destination === "string" &&
                                destination.startsWith("#")
                              ) {
                                document
                                  .getElementById(destination.substr(1))
                                  .scrollIntoView({ behavior: "smooth" });
                              } else {
                                location.assign(destination);
                              }
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["goToHomepage"] != null &&
                        typeof $steps["goToHomepage"] === "object" &&
                        typeof $steps["goToHomepage"].then === "function"
                      ) {
                        $steps["goToHomepage"] = await $steps["goToHomepage"];
                      }
                    }}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__mwUuA)}
                      displayHeight={"auto"}
                      displayMaxHeight={"275px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"275px"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: image31Nq0AaRzFlL,
                        fullWidth: 1024,
                        fullHeight: 739,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__t1Kmq)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fsOgc
                        )}
                      >
                        {"Ramen"}
                      </div>
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__sjwMn
                        )}
                      >
                        {"Food Blog Title 1"}
                      </h3>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__vvcFk)}>
                  <div
                    data-plasmic-name={"blogCard5"}
                    data-plasmic-override={overrides.blogCard5}
                    className={classNames(projectcss.all, sty.blogCard5)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__jYhuh)}
                      displayHeight={"auto"}
                      displayMaxHeight={"275px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"275px"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: image4ChZz2ZI7IrSj,
                        fullWidth: 1356,
                        fullHeight: 668,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__giyjM)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2Sn6Y
                        )}
                      >
                        {"Drinks"}
                      </div>
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__qpIe5
                        )}
                      >
                        {"Food Blog Title 2"}
                      </h3>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__pyElL)}>
                  <div
                    data-plasmic-name={"blogCard2"}
                    data-plasmic-override={overrides.blogCard2}
                    className={classNames(projectcss.all, sty.blogCard2)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___1Vvkp)}
                      displayHeight={"auto"}
                      displayMaxHeight={"275px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"275px"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: image5DtXZoSdgy4Iq,
                        fullWidth: 300,
                        fullHeight: 168,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__hd2Wp)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__do8Ra
                        )}
                      >
                        {"Organic"}
                      </div>
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__vUvh
                        )}
                      >
                        {"Food Blog Title 3"}
                      </h3>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column___5QNwV)}>
                  <div
                    data-plasmic-name={"blogCard3"}
                    data-plasmic-override={overrides.blogCard3}
                    className={classNames(projectcss.all, sty.blogCard3)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__w3L35)}
                      displayHeight={"auto"}
                      displayMaxHeight={"275px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"275px"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: image60S8ELaRh2RHd,
                        fullWidth: 673,
                        fullHeight: 448,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__iJivR)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2Botl
                        )}
                      >
                        {"Seafood"}
                      </div>
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__ko8Dq
                        )}
                      >
                        {"Food Blog Title 4"}
                      </h3>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column___7D4DM)}>
                  <div
                    data-plasmic-name={"blogCard4"}
                    data-plasmic-override={overrides.blogCard4}
                    className={classNames(projectcss.all, sty.blogCard4)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__coKoY)}
                      displayHeight={"auto"}
                      displayMaxHeight={"275px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"275px"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: image7WwGrmnh8YS,
                        fullWidth: 1600,
                        fullHeight: 1076,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__gTuFp)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qi5BH
                        )}
                      >
                        {"dinner"}
                      </div>
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__z9BTu
                        )}
                      >
                        {"Food Blog Title 5"}
                      </h3>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__mbZxp)}>
                  <div
                    data-plasmic-name={"blogCard6"}
                    data-plasmic-override={overrides.blogCard6}
                    className={classNames(projectcss.all, sty.blogCard6)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__sk3Fw)}
                      displayHeight={"auto"}
                      displayMaxHeight={"275px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"275px"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: image8TqfoWSxQcGs,
                        fullWidth: 700,
                        fullHeight: 400,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox___0CJ2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5ZrOu
                        )}
                      >
                        {"italian"}
                      </div>
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3___0A9Em
                        )}
                      >
                        {"Food Blog Title 6"}
                      </h3>
                    </div>
                  </div>
                </div>
              </Stack__>
            </div>
          </div>
          <div
            data-plasmic-name={"popularCategories"}
            data-plasmic-override={overrides.popularCategories}
            className={classNames(projectcss.all, sty.popularCategories)}
          >
            <div
              data-plasmic-name={"container4"}
              data-plasmic-override={overrides.container4}
              className={classNames(projectcss.all, sty.container4)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__vPVdi
                )}
              >
                {"Explore popular tags"}
              </h2>
              <Stack__
                as={"div"}
                data-plasmic-name={"row3"}
                data-plasmic-override={overrides.row3}
                hasGap={true}
                className={classNames(projectcss.all, sty.row3)}
              >
                <div className={classNames(projectcss.all, sty.column__i28D3)}>
                  <div
                    data-plasmic-name={"card"}
                    data-plasmic-override={overrides.card}
                    className={classNames(projectcss.all, sty.card)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ii7Dj)}
                    >
                      <Icon6Icon
                        className={classNames(projectcss.all, sty.svg__pGwJl)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__onUxx
                      )}
                    >
                      {"PASTA / NOODLES"}
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__j6Tc2)}>
                  <div
                    data-plasmic-name={"card2"}
                    data-plasmic-override={overrides.card2}
                    className={classNames(projectcss.all, sty.card2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___3NuRi
                      )}
                    >
                      <Icon7Icon
                        className={classNames(projectcss.all, sty.svg__ieiPt)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mdaKj
                      )}
                    >
                      {"BEVERAGES"}
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__f5Wzf)}>
                  <div
                    data-plasmic-name={"card3"}
                    data-plasmic-override={overrides.card3}
                    className={classNames(projectcss.all, sty.card3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___9BBtB
                      )}
                    >
                      <Icon8Icon
                        className={classNames(projectcss.all, sty.svg__qbab)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qqJmj
                      )}
                    >
                      {"VEGAN"}
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__kQ4LN)}>
                  <div
                    data-plasmic-name={"card4"}
                    data-plasmic-override={overrides.card4}
                    className={classNames(projectcss.all, sty.card4)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__seewr)}
                    >
                      <Icon9Icon
                        className={classNames(projectcss.all, sty.svg__r5CBt)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__y2CbI
                      )}
                    >
                      {"SEAFOOD"}
                    </div>
                  </div>
                </div>
              </Stack__>
            </div>
          </div>
          <div
            data-plasmic-name={"recipes"}
            data-plasmic-override={overrides.recipes}
            className={classNames(projectcss.all, sty.recipes)}
          >
            <div
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              className={classNames(projectcss.all, sty.container6)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__mfOzs
                )}
              >
                {"Most read"}
              </h2>
              <Stack__
                as={"div"}
                data-plasmic-name={"row4"}
                data-plasmic-override={overrides.row4}
                hasGap={true}
                className={classNames(projectcss.all, sty.row4)}
              >
                <div className={classNames(projectcss.all, sty.column__lBbpz)}>
                  <div
                    data-plasmic-name={"recipesCard"}
                    data-plasmic-override={overrides.recipesCard}
                    className={classNames(projectcss.all, sty.recipesCard)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__jJ6Hh)}
                      displayHeight={"auto"}
                      displayMaxHeight={"200px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"200px"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: image9MTcGgEpViCi,
                        fullWidth: 2048,
                        fullHeight: 1352,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__eE4Kw)}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3___3BXsn
                        )}
                      >
                        {"This is the title for a post"}
                      </h3>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dra95
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet,  consectetur adipisicing elit, sed do eiusmod tempor incididunt ut  labore et dolore magna aliqua."
                        }
                      </div>
                      <ThemeBtn
                        className={classNames(
                          "__wab_instance",
                          sty.themeBtn__c9RiQ
                        )}
                        color={"themebtn"}
                        endIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__eb4Ka
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__dPaLw
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yPefj
                          )}
                        >
                          {"Button"}
                        </div>
                      </ThemeBtn>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__z7Qy)}>
                  <div
                    data-plasmic-name={"recipesCard5"}
                    data-plasmic-override={overrides.recipesCard5}
                    className={classNames(projectcss.all, sty.recipesCard5)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ie3Pt)}
                      displayHeight={"auto"}
                      displayMaxHeight={"200px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"200px"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: image10MW1JukGssZH,
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___0Z3T1
                      )}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__jxjTl
                        )}
                      >
                        {"This is the title for a post"}
                      </h3>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qy7Gg
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet,  consectetur adipisicing elit, sed do eiusmod tempor incididunt ut  labore et dolore magna aliqua."
                        }
                      </div>
                      <ThemeBtn
                        className={classNames(
                          "__wab_instance",
                          sty.themeBtn__ovCt5
                        )}
                        color={"themebtn"}
                        endIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mgXgj
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__z7M5
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nPcM0
                          )}
                        >
                          {"Button"}
                        </div>
                      </ThemeBtn>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__nLSud)}>
                  <div
                    data-plasmic-name={"recipesCard6"}
                    data-plasmic-override={overrides.recipesCard6}
                    className={classNames(projectcss.all, sty.recipesCard6)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__asLdZ)}
                      displayHeight={"auto"}
                      displayMaxHeight={"200px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"200px"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: image11Aryfpjf4F29L,
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__uhks3)}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__jRbVf
                        )}
                      >
                        {"This is the title for a post"}
                      </h3>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dA0Cc
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet,  consectetur adipisicing elit, sed do eiusmod tempor incididunt ut  labore et dolore magna aliqua."
                        }
                      </div>
                      <ThemeBtn
                        className={classNames(
                          "__wab_instance",
                          sty.themeBtn___3BNzv
                        )}
                        color={"themebtn"}
                        endIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__f4Vjn
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__qf89A
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xcbbu
                          )}
                        >
                          {"Button"}
                        </div>
                      </ThemeBtn>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__x9B5)}>
                  <div
                    data-plasmic-name={"recipesCard7"}
                    data-plasmic-override={overrides.recipesCard7}
                    className={classNames(projectcss.all, sty.recipesCard7)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__itTt)}
                      displayHeight={"auto"}
                      displayMaxHeight={"200px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"200px"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: image12JImdpulIjby9,
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__rWYzn)}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__ahqMe
                        )}
                      >
                        {"This is the title for a post"}
                      </h3>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ek161
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet,  consectetur adipisicing elit, sed do eiusmod tempor incididunt ut  labore et dolore magna aliqua."
                        }
                      </div>
                      <ThemeBtn
                        className={classNames(
                          "__wab_instance",
                          sty.themeBtn__fTryW
                        )}
                        color={"themebtn"}
                        endIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mydVz
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___8Jz4L
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__u5GRt
                          )}
                        >
                          {"Button"}
                        </div>
                      </ThemeBtn>
                    </div>
                  </div>
                </div>
              </Stack__>
            </div>
          </div>
          <div
            data-plasmic-name={"newsLetter"}
            data-plasmic-override={overrides.newsLetter}
            className={classNames(projectcss.all, sty.newsLetter)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___8QCoP)}>
              <div
                data-plasmic-name={"form"}
                data-plasmic-override={overrides.form}
                className={classNames(projectcss.all, sty.form)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___8GMGz
                  )}
                >
                  {"Subscribe"}
                </h2>
                <input
                  data-plasmic-name={"textbox"}
                  data-plasmic-override={overrides.textbox}
                  className={classNames(
                    projectcss.all,
                    projectcss.input,
                    sty.textbox
                  )}
                  onChange={e => {
                    generateStateOnChangeProp($state, ["textbox", "value"])(
                      e.target.value
                    );
                  }}
                  placeholder={"Email"}
                  ref={ref => {
                    $refs["textbox"] = ref;
                  }}
                  type={"text"}
                  value={
                    generateStateValueProp($state, ["textbox", "value"]) ?? ""
                  }
                />

                <button
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames(
                    projectcss.all,
                    projectcss.button,
                    projectcss.__wab_text,
                    sty.button
                  )}
                >
                  {"Sign up"}
                </button>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___9TBa
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    "\u00a9 Company Name. All rights reserved. This site proudly built with "
                  }
                </React.Fragment>
                {
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link__uN2Sh
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"Plasmic"}
                  </PlasmicLink__>
                }

                <React.Fragment>{"."}</React.Fragment>
              </React.Fragment>
            </div>
          </div>
        </Stack__>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "logo",
    "container",
    "row",
    "menu",
    "socialSection",
    "hero",
    "container2",
    "hero2",
    "nuestroTitulo",
    "direccionesHidraulicas",
    "blog",
    "container3",
    "row2",
    "blogCard",
    "blogCard5",
    "blogCard2",
    "blogCard3",
    "blogCard4",
    "blogCard6",
    "popularCategories",
    "container4",
    "row3",
    "card",
    "card2",
    "card3",
    "card4",
    "recipes",
    "container6",
    "row4",
    "recipesCard",
    "recipesCard5",
    "recipesCard6",
    "recipesCard7",
    "newsLetter",
    "form",
    "textbox",
    "button",
    "footer"
  ],

  logo: ["logo", "container", "row", "menu", "socialSection"],
  container: ["container", "row", "menu", "socialSection"],
  row: ["row", "menu", "socialSection"],
  menu: ["menu"],
  socialSection: ["socialSection"],
  hero: ["hero", "container2"],
  container2: ["container2"],
  hero2: ["hero2", "nuestroTitulo", "direccionesHidraulicas"],
  nuestroTitulo: ["nuestroTitulo"],
  direccionesHidraulicas: ["direccionesHidraulicas"],
  blog: [
    "blog",
    "container3",
    "row2",
    "blogCard",
    "blogCard5",
    "blogCard2",
    "blogCard3",
    "blogCard4",
    "blogCard6"
  ],

  container3: [
    "container3",
    "row2",
    "blogCard",
    "blogCard5",
    "blogCard2",
    "blogCard3",
    "blogCard4",
    "blogCard6"
  ],

  row2: [
    "row2",
    "blogCard",
    "blogCard5",
    "blogCard2",
    "blogCard3",
    "blogCard4",
    "blogCard6"
  ],

  blogCard: ["blogCard"],
  blogCard5: ["blogCard5"],
  blogCard2: ["blogCard2"],
  blogCard3: ["blogCard3"],
  blogCard4: ["blogCard4"],
  blogCard6: ["blogCard6"],
  popularCategories: [
    "popularCategories",
    "container4",
    "row3",
    "card",
    "card2",
    "card3",
    "card4"
  ],

  container4: ["container4", "row3", "card", "card2", "card3", "card4"],
  row3: ["row3", "card", "card2", "card3", "card4"],
  card: ["card"],
  card2: ["card2"],
  card3: ["card3"],
  card4: ["card4"],
  recipes: [
    "recipes",
    "container6",
    "row4",
    "recipesCard",
    "recipesCard5",
    "recipesCard6",
    "recipesCard7"
  ],

  container6: [
    "container6",
    "row4",
    "recipesCard",
    "recipesCard5",
    "recipesCard6",
    "recipesCard7"
  ],

  row4: ["row4", "recipesCard", "recipesCard5", "recipesCard6", "recipesCard7"],
  recipesCard: ["recipesCard"],
  recipesCard5: ["recipesCard5"],
  recipesCard6: ["recipesCard6"],
  recipesCard7: ["recipesCard7"],
  newsLetter: ["newsLetter", "form", "textbox", "button"],
  form: ["form", "textbox", "button"],
  textbox: ["textbox"],
  button: ["button"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicListadoDeProductos__ArgProps,
          internalVariantPropNames: PlasmicListadoDeProductos__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicListadoDeProductos__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicListadoDeProductos";
  } else {
    func.displayName = `PlasmicListadoDeProductos.${nodeName}`;
  }
  return func;
}

export const PlasmicListadoDeProductos = Object.assign(
  // Top-level PlasmicListadoDeProductos renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    logo: makeNodeComponent("logo"),
    container: makeNodeComponent("container"),
    row: makeNodeComponent("row"),
    menu: makeNodeComponent("menu"),
    socialSection: makeNodeComponent("socialSection"),
    hero: makeNodeComponent("hero"),
    container2: makeNodeComponent("container2"),
    hero2: makeNodeComponent("hero2"),
    nuestroTitulo: makeNodeComponent("nuestroTitulo"),
    direccionesHidraulicas: makeNodeComponent("direccionesHidraulicas"),
    blog: makeNodeComponent("blog"),
    container3: makeNodeComponent("container3"),
    row2: makeNodeComponent("row2"),
    blogCard: makeNodeComponent("blogCard"),
    blogCard5: makeNodeComponent("blogCard5"),
    blogCard2: makeNodeComponent("blogCard2"),
    blogCard3: makeNodeComponent("blogCard3"),
    blogCard4: makeNodeComponent("blogCard4"),
    blogCard6: makeNodeComponent("blogCard6"),
    popularCategories: makeNodeComponent("popularCategories"),
    container4: makeNodeComponent("container4"),
    row3: makeNodeComponent("row3"),
    card: makeNodeComponent("card"),
    card2: makeNodeComponent("card2"),
    card3: makeNodeComponent("card3"),
    card4: makeNodeComponent("card4"),
    recipes: makeNodeComponent("recipes"),
    container6: makeNodeComponent("container6"),
    row4: makeNodeComponent("row4"),
    recipesCard: makeNodeComponent("recipesCard"),
    recipesCard5: makeNodeComponent("recipesCard5"),
    recipesCard6: makeNodeComponent("recipesCard6"),
    recipesCard7: makeNodeComponent("recipesCard7"),
    newsLetter: makeNodeComponent("newsLetter"),
    form: makeNodeComponent("form"),
    textbox: makeNodeComponent("textbox"),
    button: makeNodeComponent("button"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicListadoDeProductos
    internalVariantProps: PlasmicListadoDeProductos__VariantProps,
    internalArgProps: PlasmicListadoDeProductos__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "listado-de-productos",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicListadoDeProductos;
/* prettier-ignore-end */
