// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8hJWALBkKUeeBQwPGDeQHS
// Component: Gg20TNQjnwiE
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateStateOnChangeProp,
  generateStateValueProp,
  hasVariant,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import ThemeBtn from "../../ThemeBtn"; // plasmic-import: OFOxy67RyMdT/component
import { useScreenVariants as useScreenVariantso8ReeXvTrpRu } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: o8REEXvTrpRu/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 8hJWALBkKUeeBQwPGDeQHS/projectcss
import sty from "./PlasmicListadoDeProductos.module.css"; // plasmic-import: Gg20TNQjnwiE/css
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: LvBixuLJ8d5o/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: UEYjHwO6Y9Mk/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: HTOOEs3MCSuB/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: CWXe1ywOBmQJ/icon
import auto1JpgBqhDtf1MTdnZ from "./images/auto1Jpg.jpg"; // plasmic-import: BQHDtf1MTdnZ/picture
import auto2JpgAQjJa2SzGbV from "./images/auto2Jpg.jpg"; // plasmic-import: aQJJa2SzGbV_/picture
import _2024SilveradoEvRst0221641471166Jpg5GWzmuPbn5Zn from "./images/_2024SilveradoEvRst0221641471166Jpg.jpg"; // plasmic-import: 5gWzmuPBN5zn/picture
import auto3JpgMK3Rpt4QE5H9 from "./images/auto3Jpg.jpg"; // plasmic-import: mK3RPT4qE5h9/picture
import _202204171125046545E44230891665R15815239647451221381321737Jpeg172596871Webp7ZcjYxv56K from "./images/_202204171125046545E44230891665R15815239647451221381321737Jpeg172596871Webp.webp"; // plasmic-import: 7-ZCJ-yxv56K/picture
import auto6JpgJcz1GEtj5Tfh from "./images/auto6Jpg.jpg"; // plasmic-import: jcz1gEtj5tfh/picture
import hyundaiJpgCFn3Vjf7V4N4 from "./images/hyundaiJpg.jpg"; // plasmic-import: CFn3vjf7v4n4/picture
import hondaJpgZ0XRfKyTLdH8 from "./images/hondaJpg.jpg"; // plasmic-import: Z0xRfKyTLdH8/picture
import mercedesJpgQeYK023WXdy from "./images/mercedesJpg.jpg"; // plasmic-import: QeY-K023wXDY/picture
import kia2JpgY24WbPaNkgjJ from "./images/kia2Jpg.jpg"; // plasmic-import: Y24WbPANkgjJ/picture
import mitsubishiJpgKSssEef4FJGu from "./images/mitsubishiJpg.jpg"; // plasmic-import: KSssEEF4fJGu/picture
import mazdaJpegQriwsc807SEq from "./images/mazdaJpeg.jpg"; // plasmic-import: QRIWSC807sEq/picture
import peugeotJpgUlwMzXrAgfrr from "./images/peugeotJpg.jpg"; // plasmic-import: UlwMZXrAGFRR/picture
import nissanAriyaJpgXhiKbSq0G2Hg from "./images/nissanAriyaJpg.jpg"; // plasmic-import: XHIKbSq0G2Hg/picture
import mgJpgUCoPXf4Qg35 from "./images/mgJpg.jpg"; // plasmic-import: uCo-pXF4qg35/picture
import renoJpgU2WUf61QnYjk from "./images/renoJpg.jpg"; // plasmic-import: u2wUf61qnYJK/picture
import seatJpgFjXkXol8XRjY from "./images/seatJpg.jpg"; // plasmic-import: FJXkXol8xRjY/picture
import susukiJpgRR0WsGAyisC from "./images/susukiJpg.jpg"; // plasmic-import: rR-0wsGAyisC/picture
import vwJpgIlBfmEmqxXhp from "./images/vwJpg.jpg"; // plasmic-import: ilBFMEmqxXhp/picture
import toyotaJpgI63LCnDCrn from "./images/toyotaJpg.jpg"; // plasmic-import: _I63lCn_dCrn/picture
import image9MTcGgEpViCi from "./images/image9.jpg"; // plasmic-import: m-tcGgEpViCi/picture
import image10MW1JukGssZH from "./images/image10.jpg"; // plasmic-import: mW1JukGSS-zH/picture
import image11Aryfpjf4F29L from "./images/image11.jpg"; // plasmic-import: ARYFPJF4F29L/picture
import image12JImdpulIjby9 from "./images/image12.webp"; // plasmic-import: JImdpulIJBY9/picture

createPlasmicElementProxy;

export const PlasmicListadoDeProductos__VariantProps = new Array();

export const PlasmicListadoDeProductos__ArgProps = new Array();

const $$ = {};

function PlasmicListadoDeProductos__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "textbox.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantso8ReeXvTrpRu()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <Stack__
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"logo"}
            data-plasmic-override={overrides.logo}
            className={classNames(projectcss.all, sty.logo)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames(projectcss.all, sty.container)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"row"}
                data-plasmic-override={overrides.row}
                hasGap={true}
                className={classNames(projectcss.all, sty.row)}
              >
                <div className={classNames(projectcss.all, sty.column___2QTpH)}>
                  <div
                    data-plasmic-name={"menu"}
                    data-plasmic-override={overrides.menu}
                    className={classNames(projectcss.all, sty.menu)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__egjI
                      )}
                      href={"https://www.plasmic.app/"}
                      platform={"react"}
                    >
                      {"Stories"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__dTnS2
                      )}
                      href={"https://www.plasmic.app/"}
                      platform={"react"}
                    >
                      {"Categories"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__oIsf9
                      )}
                      href={"https://www.plasmic.app/"}
                      platform={"react"}
                    >
                      {"Recipes"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__s7Dxd
                      )}
                      href={"https://www.plasmic.app/"}
                      platform={"react"}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "About"
                        : "Recipes"}
                    </PlasmicLink__>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__cvtYn)}>
                  <div
                    data-plasmic-name={"socialSection"}
                    data-plasmic-override={overrides.socialSection}
                    className={classNames(projectcss.all, sty.socialSection)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kjZ3B)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__nzG7D)}
                        onClick={async event => {
                          const $steps = {};
                          $steps["goToPage"] = true
                            ? (() => {
                                const actionArgs = {};
                                return (({ destination }) => {
                                  if (
                                    typeof destination === "string" &&
                                    destination.startsWith("#")
                                  ) {
                                    document
                                      .getElementById(destination.substr(1))
                                      .scrollIntoView({ behavior: "smooth" });
                                  } else {
                                    location.assign(destination);
                                  }
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["goToPage"] != null &&
                            typeof $steps["goToPage"] === "object" &&
                            typeof $steps["goToPage"].then === "function"
                          ) {
                            $steps["goToPage"] = await $steps["goToPage"];
                          }
                        }}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__t8NxU)}
                    >
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg___3GeEm)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__svD)}
                    >
                      <Icon5Icon
                        className={classNames(projectcss.all, sty.svg__mjvlc)}
                        role={"img"}
                      />
                    </div>
                  </div>
                </div>
              </Stack__>
            </div>
          </div>
          <div
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            className={classNames(projectcss.all, sty.hero)}
          >
            <div
              data-plasmic-name={"container2"}
              data-plasmic-override={overrides.container2}
              className={classNames(projectcss.all, sty.container2)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__wpsBn)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__itezB
                  )}
                >
                  {"Choose the best."}
                </div>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__rhQj1
                  )}
                >
                  {"Healthy cooking."}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lkyNv
                  )}
                >
                  {
                    "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
                  }
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"hero2"}
            data-plasmic-override={overrides.hero2}
            className={classNames(projectcss.all, sty.hero2)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__v1Z6D)}>
              <h1
                data-plasmic-name={"direccionesHidraulicas"}
                data-plasmic-override={overrides.direccionesHidraulicas}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.direccionesHidraulicas
                )}
              >
                {""}
              </h1>
            </div>
          </div>
          <div
            data-plasmic-name={"blog"}
            data-plasmic-override={overrides.blog}
            className={classNames(projectcss.all, sty.blog)}
          >
            <div
              data-plasmic-name={"container3"}
              data-plasmic-override={overrides.container3}
              className={classNames(projectcss.all, sty.container3)}
            >
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__dvCie
                )}
              >
                {
                  "DIRECCIONES Y BOMBAS HIDRAULICAS\nSELECCIONA LA MARCA DE VEHICULO "
                }
              </h1>
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"row5"}
              data-plasmic-override={overrides.row5}
              hasGap={true}
              className={classNames(projectcss.all, sty.row5)}
            >
              <div className={classNames(projectcss.all, sty.column___9CMjY)}>
                <div
                  data-plasmic-name={"blogCard"}
                  data-plasmic-override={overrides.blogCard}
                  className={classNames(projectcss.all, sty.blogCard)}
                  onClick={async event => {
                    const $steps = {};
                    $steps["goToHomepage"] = true
                      ? (() => {
                          const actionArgs = {};
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              location.assign(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToHomepage"] != null &&
                      typeof $steps["goToHomepage"] === "object" &&
                      typeof $steps["goToHomepage"].then === "function"
                    ) {
                      $steps["goToHomepage"] = await $steps["goToHomepage"];
                    }
                  }}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__mwUuA)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: auto1JpgBqhDtf1MTdnZ,
                      fullWidth: 736,
                      fullHeight: 1308,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__t1Kmq)}
                  >
                    <div
                      data-plasmic-name={"marca"}
                      data-plasmic-override={overrides.marca}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.marca
                      )}
                    >
                      {""}
                    </div>
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__sjwMn
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 600 }}
                        >
                          {"AUDI"}
                        </span>
                      </React.Fragment>
                    </h1>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__vvcFk)}>
                <div
                  data-plasmic-name={"blogCard5"}
                  data-plasmic-override={overrides.blogCard5}
                  className={classNames(projectcss.all, sty.blogCard5)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__jYhuh)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: auto2JpgAQjJa2SzGbV,
                      fullWidth: 676,
                      fullHeight: 1201,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__giyjM)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2Sn6Y
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__qpIe5
                      )}
                    >
                      {"BMW"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__pyElL)}>
                <div
                  data-plasmic-name={"blogCard2"}
                  data-plasmic-override={overrides.blogCard2}
                  className={classNames(projectcss.all, sty.blogCard2)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___1Vvkp)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: _2024SilveradoEvRst0221641471166Jpg5GWzmuPbn5Zn,
                      fullWidth: 2500,
                      fullHeight: 1406,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__hd2Wp)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__do8Ra
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__vUvh
                      )}
                    >
                      {"CHEVROLET"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___5QNwV)}>
                <div
                  data-plasmic-name={"blogCard3"}
                  data-plasmic-override={overrides.blogCard3}
                  className={classNames(projectcss.all, sty.blogCard3)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__w3L35)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: auto3JpgMK3Rpt4QE5H9,
                      fullWidth: 736,
                      fullHeight: 1308,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__iJivR)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2Botl
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__ko8Dq
                      )}
                    >
                      {"CHRYSLER/DODGE"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___7D4DM)}>
                <div
                  data-plasmic-name={"blogCard4"}
                  data-plasmic-override={overrides.blogCard4}
                  className={classNames(projectcss.all, sty.blogCard4)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__coKoY)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: _202204171125046545E44230891665R15815239647451221381321737Jpeg172596871Webp7ZcjYxv56K,
                      fullWidth: 1200,
                      fullHeight: 740,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__gTuFp)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qi5BH
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__z9BTu
                      )}
                    >
                      {"FIAT"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__mbZxp)}>
                <div
                  data-plasmic-name={"blogCard6"}
                  data-plasmic-override={overrides.blogCard6}
                  className={classNames(projectcss.all, sty.blogCard6)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__sk3Fw)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: auto6JpgJcz1GEtj5Tfh,
                      fullWidth: 736,
                      fullHeight: 920,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox___0CJ2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5ZrOu
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___0A9Em
                      )}
                    >
                      {"FORD"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__iurd8)}>
                <div
                  data-plasmic-name={"blogCard8"}
                  data-plasmic-override={overrides.blogCard8}
                  className={classNames(projectcss.all, sty.blogCard8)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__xwvk4)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: hyundaiJpgCFn3Vjf7V4N4,
                      fullWidth: 720,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__b4OMv)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nTlde
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__nNq3O
                      )}
                    >
                      {"HYUNDAI"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__tpaXc)}>
                <div
                  data-plasmic-name={"blogCard7"}
                  data-plasmic-override={overrides.blogCard7}
                  className={classNames(projectcss.all, sty.blogCard7)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___833HF)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: hondaJpgZ0XRfKyTLdH8,
                      fullWidth: 998,
                      fullHeight: 1499,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__wp12L)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rxVbj
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__roCoD
                      )}
                    >
                      {"HONDA"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__z8NQa)}>
                <div
                  data-plasmic-name={"blogCard10"}
                  data-plasmic-override={overrides.blogCard10}
                  className={classNames(projectcss.all, sty.blogCard10)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__fbknd)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: mercedesJpgQeYK023WXdy,
                      fullWidth: 736,
                      fullHeight: 1104,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__kyCmu)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eqmE0
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__cx0GI
                      )}
                    >
                      {"MERCEDES BENZ"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___3GeeE)}>
                <div
                  data-plasmic-name={"blogCard11"}
                  data-plasmic-override={overrides.blogCard11}
                  className={classNames(projectcss.all, sty.blogCard11)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__z0Whk)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: kia2JpgY24WbPaNkgjJ,
                      fullWidth: 736,
                      fullHeight: 414,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__k2PvS)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wKbF
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__vBcdx
                      )}
                    >
                      {"KIA"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__fMf3U)}>
                <div
                  data-plasmic-name={"blogCard12"}
                  data-plasmic-override={overrides.blogCard12}
                  className={classNames(projectcss.all, sty.blogCard12)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__nzopb)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: mitsubishiJpgKSssEef4FJGu,
                      fullWidth: 675,
                      fullHeight: 1200,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__qUhBf)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__h8Jxu
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__hVS9
                      )}
                    >
                      {"MITSUBISHI"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___2U2Bo)}>
                <div
                  data-plasmic-name={"blogCard13"}
                  data-plasmic-override={overrides.blogCard13}
                  className={classNames(projectcss.all, sty.blogCard13)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__zgp0J)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: mazdaJpegQriwsc807SEq,
                      fullWidth: 736,
                      fullHeight: 736,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__sl53W)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vD2VZ
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___7NmYe
                      )}
                    >
                      {"MAZDA"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__uXiyh)}>
                <div
                  data-plasmic-name={"blogCard14"}
                  data-plasmic-override={overrides.blogCard14}
                  className={classNames(projectcss.all, sty.blogCard14)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__f7IuH)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: peugeotJpgUlwMzXrAgfrr,
                      fullWidth: 736,
                      fullHeight: 920,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox___3Gri2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uS4E
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__hWbPe
                      )}
                    >
                      {"PEUGEOT"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__qyD90)}>
                <div
                  data-plasmic-name={"blogCard15"}
                  data-plasmic-override={overrides.blogCard15}
                  className={classNames(projectcss.all, sty.blogCard15)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__pSyof)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: nissanAriyaJpgXhiKbSq0G2Hg,
                      fullWidth: 478,
                      fullHeight: 718,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__pwtvt)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yadt6
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__fiPn
                      )}
                    >
                      {"NISSAN"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__njF1)}>
                <div
                  data-plasmic-name={"blogCard16"}
                  data-plasmic-override={overrides.blogCard16}
                  className={classNames(projectcss.all, sty.blogCard16)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__romer)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: mgJpgUCoPXf4Qg35,
                      fullWidth: 735,
                      fullHeight: 490,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__ztZaz)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rGp1Z
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__dBi
                      )}
                    >
                      {"MG"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__waDgP)}>
                <div
                  data-plasmic-name={"blogCard17"}
                  data-plasmic-override={overrides.blogCard17}
                  className={classNames(projectcss.all, sty.blogCard17)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__fnnlu)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: renoJpgU2WUf61QnYjk,
                      fullWidth: 364,
                      fullHeight: 205,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__ejxI)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__b4BbE
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__ncfdC
                      )}
                    >
                      {"RENAULT"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__mmHkq)}>
                <div
                  data-plasmic-name={"blogCard18"}
                  data-plasmic-override={overrides.blogCard18}
                  className={classNames(projectcss.all, sty.blogCard18)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__lFkk)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: seatJpgFjXkXol8XRjY,
                      fullWidth: 735,
                      fullHeight: 1306,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__aaNex)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fnHN
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__k6H1H
                      )}
                    >
                      {"SEAT"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__pJplR)}>
                <div
                  data-plasmic-name={"blogCard19"}
                  data-plasmic-override={overrides.blogCard19}
                  className={classNames(projectcss.all, sty.blogCard19)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__j0L5E)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: susukiJpgRR0WsGAyisC,
                      fullWidth: 735,
                      fullHeight: 919,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__qefPb)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kXm7L
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__pqNz
                      )}
                    >
                      {"SUSUKI"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__x8IsN)}>
                <div
                  data-plasmic-name={"blogCard20"}
                  data-plasmic-override={overrides.blogCard20}
                  className={classNames(projectcss.all, sty.blogCard20)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__u7Yl0)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: vwJpgIlBfmEmqxXhp,
                      fullWidth: 736,
                      fullHeight: 736,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__hCj0D)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kICx
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__wzEj4
                      )}
                    >
                      {"VOLKSWAGEN"}
                    </h3>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___23G3G)}>
                <div
                  data-plasmic-name={"blogCard21"}
                  data-plasmic-override={overrides.blogCard21}
                  className={classNames(projectcss.all, sty.blogCard21)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__njyP)}
                    displayHeight={"auto"}
                    displayMaxHeight={"275px"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"275px"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: toyotaJpgI63LCnDCrn,
                      fullWidth: 735,
                      fullHeight: 687,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__saRQs)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__q96P
                      )}
                    >
                      {""}
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__uffQ6
                      )}
                    >
                      {"TOYOTA"}
                    </h3>
                  </div>
                </div>
              </div>
            </Stack__>
          </div>
          <div
            data-plasmic-name={"popularCategories"}
            data-plasmic-override={overrides.popularCategories}
            className={classNames(projectcss.all, sty.popularCategories)}
          >
            <div
              data-plasmic-name={"container4"}
              data-plasmic-override={overrides.container4}
              className={classNames(projectcss.all, sty.container4)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__vPVdi
                )}
              >
                {"VISITANOS EN:"}
              </h2>
              <Stack__
                as={"div"}
                data-plasmic-name={"row3"}
                data-plasmic-override={overrides.row3}
                hasGap={true}
                className={classNames(projectcss.all, sty.row3)}
              >
                <div className={classNames(projectcss.all, sty.column__i28D3)}>
                  <div
                    data-plasmic-name={"card"}
                    data-plasmic-override={overrides.card}
                    className={classNames(projectcss.all, sty.card)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ii7Dj)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__onUxx
                      )}
                    >
                      {""}
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__j6Tc2)}>
                  <div
                    data-plasmic-name={"card2"}
                    data-plasmic-override={overrides.card2}
                    className={classNames(projectcss.all, sty.card2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___3NuRi
                      )}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mdaKj
                      )}
                    >
                      {""}
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__f5Wzf)}>
                  <div
                    data-plasmic-name={"card3"}
                    data-plasmic-override={overrides.card3}
                    className={classNames(projectcss.all, sty.card3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___9BBtB
                      )}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qqJmj
                      )}
                    >
                      {""}
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__kQ4LN)}>
                  <div
                    data-plasmic-name={"card4"}
                    data-plasmic-override={overrides.card4}
                    className={classNames(projectcss.all, sty.card4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__y2CbI
                      )}
                    >
                      {""}
                    </div>
                  </div>
                </div>
              </Stack__>
            </div>
          </div>
          <div
            data-plasmic-name={"recipes"}
            data-plasmic-override={overrides.recipes}
            className={classNames(projectcss.all, sty.recipes)}
          >
            <div
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              className={classNames(projectcss.all, sty.container6)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__mfOzs
                )}
              >
                {"Most read"}
              </h2>
              <Stack__
                as={"div"}
                data-plasmic-name={"row4"}
                data-plasmic-override={overrides.row4}
                hasGap={true}
                className={classNames(projectcss.all, sty.row4)}
              >
                <div className={classNames(projectcss.all, sty.column__lBbpz)}>
                  <div
                    data-plasmic-name={"recipesCard"}
                    data-plasmic-override={overrides.recipesCard}
                    className={classNames(projectcss.all, sty.recipesCard)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__jJ6Hh)}
                      displayHeight={"auto"}
                      displayMaxHeight={"200px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"200px"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: image9MTcGgEpViCi,
                        fullWidth: 2048,
                        fullHeight: 1352,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__eE4Kw)}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3___3BXsn
                        )}
                      >
                        {"This is the title for a post"}
                      </h3>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dra95
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet,  consectetur adipisicing elit, sed do eiusmod tempor incididunt ut  labore et dolore magna aliqua."
                        }
                      </div>
                      <ThemeBtn
                        className={classNames(
                          "__wab_instance",
                          sty.themeBtn__c9RiQ
                        )}
                        color={"themebtn"}
                        endIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__eb4Ka
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__dPaLw
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yPefj
                          )}
                        >
                          {"Button"}
                        </div>
                      </ThemeBtn>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__z7Qy)}>
                  <div
                    data-plasmic-name={"recipesCard5"}
                    data-plasmic-override={overrides.recipesCard5}
                    className={classNames(projectcss.all, sty.recipesCard5)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ie3Pt)}
                      displayHeight={"auto"}
                      displayMaxHeight={"200px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"200px"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: image10MW1JukGssZH,
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___0Z3T1
                      )}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__jxjTl
                        )}
                      >
                        {"This is the title for a post"}
                      </h3>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qy7Gg
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet,  consectetur adipisicing elit, sed do eiusmod tempor incididunt ut  labore et dolore magna aliqua."
                        }
                      </div>
                      <ThemeBtn
                        className={classNames(
                          "__wab_instance",
                          sty.themeBtn__ovCt5
                        )}
                        color={"themebtn"}
                        endIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mgXgj
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__z7M5
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nPcM0
                          )}
                        >
                          {"Button"}
                        </div>
                      </ThemeBtn>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__nLSud)}>
                  <div
                    data-plasmic-name={"recipesCard6"}
                    data-plasmic-override={overrides.recipesCard6}
                    className={classNames(projectcss.all, sty.recipesCard6)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__asLdZ)}
                      displayHeight={"auto"}
                      displayMaxHeight={"200px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"200px"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: image11Aryfpjf4F29L,
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__uhks3)}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__jRbVf
                        )}
                      >
                        {"This is the title for a post"}
                      </h3>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dA0Cc
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet,  consectetur adipisicing elit, sed do eiusmod tempor incididunt ut  labore et dolore magna aliqua."
                        }
                      </div>
                      <ThemeBtn
                        className={classNames(
                          "__wab_instance",
                          sty.themeBtn___3BNzv
                        )}
                        color={"themebtn"}
                        endIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__f4Vjn
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__qf89A
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xcbbu
                          )}
                        >
                          {"Button"}
                        </div>
                      </ThemeBtn>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__x9B5)}>
                  <div
                    data-plasmic-name={"recipesCard7"}
                    data-plasmic-override={overrides.recipesCard7}
                    className={classNames(projectcss.all, sty.recipesCard7)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__itTt)}
                      displayHeight={"auto"}
                      displayMaxHeight={"200px"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"200px"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: image12JImdpulIjby9,
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__rWYzn)}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__ahqMe
                        )}
                      >
                        {"This is the title for a post"}
                      </h3>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ek161
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet,  consectetur adipisicing elit, sed do eiusmod tempor incididunt ut  labore et dolore magna aliqua."
                        }
                      </div>
                      <ThemeBtn
                        className={classNames(
                          "__wab_instance",
                          sty.themeBtn__fTryW
                        )}
                        color={"themebtn"}
                        endIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mydVz
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___8Jz4L
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__u5GRt
                          )}
                        >
                          {"Button"}
                        </div>
                      </ThemeBtn>
                    </div>
                  </div>
                </div>
              </Stack__>
            </div>
          </div>
          <div
            data-plasmic-name={"newsLetter"}
            data-plasmic-override={overrides.newsLetter}
            className={classNames(projectcss.all, sty.newsLetter)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___8QCoP)}>
              <div
                data-plasmic-name={"form"}
                data-plasmic-override={overrides.form}
                className={classNames(projectcss.all, sty.form)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___8GMGz
                  )}
                >
                  {"Subscribe"}
                </h2>
                <input
                  data-plasmic-name={"textbox"}
                  data-plasmic-override={overrides.textbox}
                  className={classNames(
                    projectcss.all,
                    projectcss.input,
                    sty.textbox
                  )}
                  onChange={e => {
                    generateStateOnChangeProp($state, ["textbox", "value"])(
                      e.target.value
                    );
                  }}
                  placeholder={"Email"}
                  ref={ref => {
                    $refs["textbox"] = ref;
                  }}
                  type={"text"}
                  value={
                    generateStateValueProp($state, ["textbox", "value"]) ?? ""
                  }
                />

                <button
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames(
                    projectcss.all,
                    projectcss.button,
                    projectcss.__wab_text,
                    sty.button
                  )}
                >
                  {"Sign up"}
                </button>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___9TBa
              )}
            >
              <React.Fragment>
                <React.Fragment>
                  {
                    "\u00a9 Company Name. All rights reserved. This site proudly built with "
                  }
                </React.Fragment>
                {
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.link__uN2Sh
                    )}
                    href={"https://www.plasmic.app/"}
                    platform={"react"}
                  >
                    {"Plasmic"}
                  </PlasmicLink__>
                }

                <React.Fragment>{"."}</React.Fragment>
              </React.Fragment>
            </div>
          </div>
        </Stack__>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "logo",
    "container",
    "row",
    "menu",
    "socialSection",
    "hero",
    "container2",
    "hero2",
    "direccionesHidraulicas",
    "blog",
    "container3",
    "row5",
    "blogCard",
    "marca",
    "blogCard5",
    "blogCard2",
    "blogCard3",
    "blogCard4",
    "blogCard6",
    "blogCard8",
    "blogCard7",
    "blogCard10",
    "blogCard11",
    "blogCard12",
    "blogCard13",
    "blogCard14",
    "blogCard15",
    "blogCard16",
    "blogCard17",
    "blogCard18",
    "blogCard19",
    "blogCard20",
    "blogCard21",
    "popularCategories",
    "container4",
    "row3",
    "card",
    "card2",
    "card3",
    "card4",
    "recipes",
    "container6",
    "row4",
    "recipesCard",
    "recipesCard5",
    "recipesCard6",
    "recipesCard7",
    "newsLetter",
    "form",
    "textbox",
    "button",
    "footer"
  ],

  logo: ["logo", "container", "row", "menu", "socialSection"],
  container: ["container", "row", "menu", "socialSection"],
  row: ["row", "menu", "socialSection"],
  menu: ["menu"],
  socialSection: ["socialSection"],
  hero: ["hero", "container2"],
  container2: ["container2"],
  hero2: ["hero2", "direccionesHidraulicas"],
  direccionesHidraulicas: ["direccionesHidraulicas"],
  blog: [
    "blog",
    "container3",
    "row5",
    "blogCard",
    "marca",
    "blogCard5",
    "blogCard2",
    "blogCard3",
    "blogCard4",
    "blogCard6",
    "blogCard8",
    "blogCard7",
    "blogCard10",
    "blogCard11",
    "blogCard12",
    "blogCard13",
    "blogCard14",
    "blogCard15",
    "blogCard16",
    "blogCard17",
    "blogCard18",
    "blogCard19",
    "blogCard20",
    "blogCard21"
  ],

  container3: ["container3"],
  row5: [
    "row5",
    "blogCard",
    "marca",
    "blogCard5",
    "blogCard2",
    "blogCard3",
    "blogCard4",
    "blogCard6",
    "blogCard8",
    "blogCard7",
    "blogCard10",
    "blogCard11",
    "blogCard12",
    "blogCard13",
    "blogCard14",
    "blogCard15",
    "blogCard16",
    "blogCard17",
    "blogCard18",
    "blogCard19",
    "blogCard20",
    "blogCard21"
  ],

  blogCard: ["blogCard", "marca"],
  marca: ["marca"],
  blogCard5: ["blogCard5"],
  blogCard2: ["blogCard2"],
  blogCard3: ["blogCard3"],
  blogCard4: ["blogCard4"],
  blogCard6: ["blogCard6"],
  blogCard8: ["blogCard8"],
  blogCard7: ["blogCard7"],
  blogCard10: ["blogCard10"],
  blogCard11: ["blogCard11"],
  blogCard12: ["blogCard12"],
  blogCard13: ["blogCard13"],
  blogCard14: ["blogCard14"],
  blogCard15: ["blogCard15"],
  blogCard16: ["blogCard16"],
  blogCard17: ["blogCard17"],
  blogCard18: ["blogCard18"],
  blogCard19: ["blogCard19"],
  blogCard20: ["blogCard20"],
  blogCard21: ["blogCard21"],
  popularCategories: [
    "popularCategories",
    "container4",
    "row3",
    "card",
    "card2",
    "card3",
    "card4"
  ],

  container4: ["container4", "row3", "card", "card2", "card3", "card4"],
  row3: ["row3", "card", "card2", "card3", "card4"],
  card: ["card"],
  card2: ["card2"],
  card3: ["card3"],
  card4: ["card4"],
  recipes: [
    "recipes",
    "container6",
    "row4",
    "recipesCard",
    "recipesCard5",
    "recipesCard6",
    "recipesCard7"
  ],

  container6: [
    "container6",
    "row4",
    "recipesCard",
    "recipesCard5",
    "recipesCard6",
    "recipesCard7"
  ],

  row4: ["row4", "recipesCard", "recipesCard5", "recipesCard6", "recipesCard7"],
  recipesCard: ["recipesCard"],
  recipesCard5: ["recipesCard5"],
  recipesCard6: ["recipesCard6"],
  recipesCard7: ["recipesCard7"],
  newsLetter: ["newsLetter", "form", "textbox", "button"],
  form: ["form", "textbox", "button"],
  textbox: ["textbox"],
  button: ["button"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicListadoDeProductos__ArgProps,
          internalVariantPropNames: PlasmicListadoDeProductos__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicListadoDeProductos__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicListadoDeProductos";
  } else {
    func.displayName = `PlasmicListadoDeProductos.${nodeName}`;
  }
  return func;
}

export const PlasmicListadoDeProductos = Object.assign(
  // Top-level PlasmicListadoDeProductos renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    logo: makeNodeComponent("logo"),
    container: makeNodeComponent("container"),
    row: makeNodeComponent("row"),
    menu: makeNodeComponent("menu"),
    socialSection: makeNodeComponent("socialSection"),
    hero: makeNodeComponent("hero"),
    container2: makeNodeComponent("container2"),
    hero2: makeNodeComponent("hero2"),
    direccionesHidraulicas: makeNodeComponent("direccionesHidraulicas"),
    blog: makeNodeComponent("blog"),
    container3: makeNodeComponent("container3"),
    row5: makeNodeComponent("row5"),
    blogCard: makeNodeComponent("blogCard"),
    marca: makeNodeComponent("marca"),
    blogCard5: makeNodeComponent("blogCard5"),
    blogCard2: makeNodeComponent("blogCard2"),
    blogCard3: makeNodeComponent("blogCard3"),
    blogCard4: makeNodeComponent("blogCard4"),
    blogCard6: makeNodeComponent("blogCard6"),
    blogCard8: makeNodeComponent("blogCard8"),
    blogCard7: makeNodeComponent("blogCard7"),
    blogCard10: makeNodeComponent("blogCard10"),
    blogCard11: makeNodeComponent("blogCard11"),
    blogCard12: makeNodeComponent("blogCard12"),
    blogCard13: makeNodeComponent("blogCard13"),
    blogCard14: makeNodeComponent("blogCard14"),
    blogCard15: makeNodeComponent("blogCard15"),
    blogCard16: makeNodeComponent("blogCard16"),
    blogCard17: makeNodeComponent("blogCard17"),
    blogCard18: makeNodeComponent("blogCard18"),
    blogCard19: makeNodeComponent("blogCard19"),
    blogCard20: makeNodeComponent("blogCard20"),
    blogCard21: makeNodeComponent("blogCard21"),
    popularCategories: makeNodeComponent("popularCategories"),
    container4: makeNodeComponent("container4"),
    row3: makeNodeComponent("row3"),
    card: makeNodeComponent("card"),
    card2: makeNodeComponent("card2"),
    card3: makeNodeComponent("card3"),
    card4: makeNodeComponent("card4"),
    recipes: makeNodeComponent("recipes"),
    container6: makeNodeComponent("container6"),
    row4: makeNodeComponent("row4"),
    recipesCard: makeNodeComponent("recipesCard"),
    recipesCard5: makeNodeComponent("recipesCard5"),
    recipesCard6: makeNodeComponent("recipesCard6"),
    recipesCard7: makeNodeComponent("recipesCard7"),
    newsLetter: makeNodeComponent("newsLetter"),
    form: makeNodeComponent("form"),
    textbox: makeNodeComponent("textbox"),
    button: makeNodeComponent("button"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicListadoDeProductos
    internalVariantProps: PlasmicListadoDeProductos__VariantProps,
    internalArgProps: PlasmicListadoDeProductos__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "listado-de-productos",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicListadoDeProductos;
/* prettier-ignore-end */
